# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/client_telemetry_ids.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/enums/client_telemetry_ids.proto',
  package='pogoprotos.enums',
  syntax='proto3',
  serialized_pb=_b('\n+pogoprotos/enums/client_telemetry_ids.proto\x12\x10pogoprotos.enums*B\n\x12\x43lientTelemetryIds\x12\r\n\tUNDEFINED\x10\x00\x12\r\n\tBOOT_TIME\x10\x01\x12\x0e\n\nFRAME_RATE\x10\x02\x62\x06proto3')
)

_CLIENTTELEMETRYIDS = _descriptor.EnumDescriptor(
  name='ClientTelemetryIds',
  full_name='pogoprotos.enums.ClientTelemetryIds',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOT_TIME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRAME_RATE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=65,
  serialized_end=131,
)
_sym_db.RegisterEnumDescriptor(_CLIENTTELEMETRYIDS)

ClientTelemetryIds = enum_type_wrapper.EnumTypeWrapper(_CLIENTTELEMETRYIDS)
UNDEFINED = 0
BOOT_TIME = 1
FRAME_RATE = 2


DESCRIPTOR.enum_types_by_name['ClientTelemetryIds'] = _CLIENTTELEMETRYIDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
